In [2]:
%load_ext autoreload
%autoreload 2

import os, sys

# Load imports from the src directory
sys.path.insert(0, "../..")

In [13]:
from progsnap2.spec.spec_definition import PS2Versions

spec = PS2Versions.v1_0.load()

In [3]:
from progsnap2.database.config import PS2DataConfig
from progsnap2.spec.metadata import MetadataValues

config = PS2DataConfig(
    root_path="../../../sample_data/codeworkout/f19",
    main_table_file="MainTable.csv",
    codestates_table_relative_path="LinkTables/CodeStates.csv",
    metadata=MetadataValues(
        IsEventOrderingConsistent=True,
        EventOrderScope="Global",
    )
)

In [15]:
from progsnap2.analytics.ps2_dataset import PS2Dataset

dataset_from_obj = PS2Dataset(spec, config)
# Note, here you can add preprocessors if desired
dataset_from_obj.get_main_table_head()

Warning: Invalid timezone offset '0' for 'ServerTimestamp' value '2019-09-23T15:15:13'. Skipping future warnings.

,SubjectID,ToolInstances,ServerTimestamp,ServerTimezone,CourseID,AssignmentID,ProblemID,Attempt,CodeStateID,IsEventOrderingConsistent,EventType,Score,Compile.Result,CompileMessageType,CompileMessageData,EventID,Order,ParentEventID
0,fd8111a7935742d5d198fb6ba2224bf1b772974b7c17e1...,Java 8; CodeWorkout,2019-09-23 15:14:44,0,CS 1,597,13,1,e03c3817ba234c667140a5281960bfc79238ef075b48c7...,True,Run.Program,0.0,NaN,NaN,NaN,0,0,NaN
1,fd8111a7935742d5d198fb6ba2224bf1b772974b7c17e1...,Java 8; CodeWorkout,2019-09-23 15:14:44,0,CS 1,597,13,1,e03c3817ba234c667140a5281960bfc79238ef075b48c7...,True,Compile,NaN,Error,NaN,NaN,1,1,0.0
2,fd8111a7935742d5d198fb6ba2224bf1b772974b7c17e1...,Java 8; CodeWorkout,2019-09-23 15:14:44,0,CS 1,597,13,1,e03c3817ba234c667140a5281960bfc79238ef075b48c7...,True,Compile.Error,NaN,NaN,SyntaxError,line 18: error: missing return statement,2,2,1.0
3,fd8111a7935742d5d198fb6ba2224bf1b772974b7c17e1...,Java 8; CodeWorkout,2019-09-23 15:15:13,0,CS 1,597,13,2,cdfe99579672f04db808aa7343826bf3c71751dfba129d...,True,Run.Program,0.0,NaN,NaN,NaN,3,3,NaN
4,fd8111a7935742d5d198fb6ba2224bf1b772974b7c17e1...,Java 8; CodeWorkout,2019-09-23 15:15:13,0,CS 1,597,13,2,cdfe99579672f04db808aa7343826bf3c71751dfba129d...,True,Compile,NaN,Error,NaN,NaN,4,4,3.0

In [16]:
yaml_config = PS2DataConfig.from_yaml('./custom_config.yaml', spec)
dataset_from_yaml = PS2Dataset(spec, yaml_config)
dataset_from_yaml.get_main_table_head()

Warning: Invalid timezone offset '0' for 'ServerTimestamp' value '2019-09-23T15:15:13'. Skipping future warnings.

,SubjectID,ToolInstances,ServerTimestamp,ServerTimezone,CourseID,AssignmentID,ProblemID,Attempt,CodeStateID,IsEventOrderingConsistent,EventType,Score,Compile.Result,CompileMessageType,CompileMessageData,EventID,Order,ParentEventID
0,fd8111a7935742d5d198fb6ba2224bf1b772974b7c17e1...,Java 8; CodeWorkout,2019-09-23 15:14:44,0,CS 1,597,13,1,e03c3817ba234c667140a5281960bfc79238ef075b48c7...,True,Run.Program,0.0,NaN,NaN,NaN,0,0,NaN
1,fd8111a7935742d5d198fb6ba2224bf1b772974b7c17e1...,Java 8; CodeWorkout,2019-09-23 15:14:44,0,CS 1,597,13,1,e03c3817ba234c667140a5281960bfc79238ef075b48c7...,True,Compile,NaN,Error,NaN,NaN,1,1,0.0
2,fd8111a7935742d5d198fb6ba2224bf1b772974b7c17e1...,Java 8; CodeWorkout,2019-09-23 15:14:44,0,CS 1,597,13,1,e03c3817ba234c667140a5281960bfc79238ef075b48c7...,True,Compile.Error,NaN,NaN,SyntaxError,line 18: error: missing return statement,2,2,1.0
3,fd8111a7935742d5d198fb6ba2224bf1b772974b7c17e1...,Java 8; CodeWorkout,2019-09-23 15:15:13,0,CS 1,597,13,2,cdfe99579672f04db808aa7343826bf3c71751dfba129d...,True,Run.Program,0.0,NaN,NaN,NaN,3,3,NaN
4,fd8111a7935742d5d198fb6ba2224bf1b772974b7c17e1...,Java 8; CodeWorkout,2019-09-23 15:15:13,0,CS 1,597,13,2,cdfe99579672f04db808aa7343826bf3c71751dfba129d...,True,Compile,NaN,Error,NaN,NaN,4,4,3.0